
// post api actions
export const GET_POST_REQUEST = 'GET_POST_REQUEST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAILURE = 'GET_POST_FAILURE';

export const GET_POST_OF_THE_WEEK_REQUEST = 'GET_POST_OF_THE_WEEK_REQUEST';
export const GET_POST_OF_THE_WEEK_SUCCESS = 'GET_POST_OF_THE_WEEK_SUCCESS';
export const GET_POST_OF_THE_WEEK_FAILURE = 'GET_POST_OF_THE_WEEK_FAILURE';

export const GET_TOP_SCROLLABLE_REQUEST = 'GET_TOP_SCROLLABLE_REQUEST';
export const GET_TOP_SCROLLABLE_SUCCESS = 'GET_TOP_SCROLLABLE_SUCCESS';
export const GET_TOP_SCROLLABLE_FAILURE = 'GET_TOP_SCROLLABLE_FAILURE';

export const MY_POSTS_REQUEST = 'MY_POSTS_REQUEST';
export const MY_POSTS_SUCCESS = 'MY_POSTS_SUCCESS';
export const MY_POSTS_FAILURE = 'MY_POSTS_FAILURE';

export const REMOVE_POST_REQUEST = 'REMOVE_POST_REQUEST';
export const REMOVE_POST_SUCCESS = 'REMOVE_POST_SUCCESS';
export const REMOVE_POST_FAILURE = 'REMOVE_POST_FAILURE';

export const MY_REQUESTED_ARTICLES_REQUEST = 'MY_REQUESTED_ARTICLES_REQUEST';
export const MY_REQUESTED_ARTICLES_SUCCESS = 'MY_REQUESTED_ARTICLES_SUCCESS';
export const MY_REQUESTED_ARTICLES_FAILURE = 'MY_REQUESTED_ARTICLES_FAILURE';

// submit post (i.e post creation with all the required values title, image and content).
export const SUBMIT_POST_REQUEST = 'SUBMIT_POST_REQUEST';
export const SUBMIT_POST_SUCCESS = 'SUBMIT_POST_SUCCESS';
export const SUBMIT_POST_FAILURE = 'SUBMIT_POST_FAILURE';

// new post creation
export const ADD_NEW_POST_REQUEST = 'ADD_NEW_POST_REQUEST';
export const ADD_NEW_POST_SUCCESS = 'ADD_NEW_POST_SUCCESS';
export const ADD_NEW_POST_FAILURE = 'ADD_NEW_POST_FAILURE';

// update post
export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAILURE = 'UPDATE_POST_FAILURE';

// startup api actions
export const GET_STARTUP_REQUEST = 'GET_STARTUP_REQUEST';
export const GET_STARTUP_SUCCESS = 'GET_STARTUP_SUCCESS';
export const GET_STARTUP_FAILURE = 'GET_STARTUP_FAILURE';

// Contacts API actions
export const GET_ENTITIES_REQUEST = "GET_ENTITIES_REQUEST";
export const GET_ENTITIES_SUCCESS = "GET_ENTITIES_SUCCESS";
export const GET_ENTITIES_FAILURE = "GET_ENTITIES_FAILURE";

export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";

export const GET_CONTACTS_OF_CATEGORIES_REQUEST = "GET_CONTACTS_OF_CATEGORIES_REQUEST";
export const GET_CONTACTS_OF_CATEGORIES_SUCCESS = "GET_CONTACTS_OF_CATEGORIES_SUCCESS";
export const GET_CONTACTS_OF_CATEGORIES_FAILURE = "GET_CONTACTS_OF_CATEGORIES_FAILURE";

//auth actions
export const LOGIN_WITH_MOBILE_NUMBER_REQUEST = "LOGIN_WITH_MOBILE_NUMBER_REQUEST";
export const LOGIN_WITH_MOBILE_NUMBER_SUCCESS = "LOGIN_WITH_MOBILE_NUMBER_SUCCESS";
export const LOGIN_WITH_MOBILE_NUMBER_FAILURE = "LOGIN_WITH_MOBILE_NUMBER_FAILURE";

export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";

export const RESEND_OTP_REQUEST = "RESEND_OTP_REQUEST";
export const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS";
export const RESEND_OTP_FAILURE = "RESEND_OTP_FAILURE";

// verify-new-email-otp
export const VERIFY_NEW_EMAIL_OTP_REQUEST = "VERIFY_NEW_EMAIL_OTP_REQUEST";
export const VERIFY_NEW_EMAIL_OTP_SUCCESS = "VERIFY_NEW_EMAIL_OTP_SUCCESS";
export const VERIFY_NEW_EMAIL_OTP_FAILURE = "VERIFY_NEW_EMAIL_OTP_FAILURE";

// verify-new-phone-otp
export const VERIFY_NEW_PHONE_OTP_REQUEST = "VERIFY_NEW_PHONE_OTP_REQUEST";
export const VERIFY_NEW_PHONE_OTP_SUCCESS = "VERIFY_NEW_PHONE_OTP_SUCCESS";
export const VERIFY_NEW_PHONE_OTP_FAILURE = "VERIFY_NEW_PHONE_OTP_FAILURE";

// user profile
export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILURE = "USER_PROFILE_FAILURE";

// user logout
export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";

// user image update
export const USER_IMAGE_UPDATE_REQUEST = "USER_IMAGE_UPDATE_REQUEST";
export const USER_IMAGE_UPDATE_SUCCESS = "USER_IMAGE_UPDATE_SUCCESS";
export const USER_IMAGE_UPDATE_FAILURE = "USER_IMAGE_UPDATE_FAILURE";

// toggle-notification
export const TOGGLE_NOTIFICATION_REQUEST = "TOGGLE_NOTIFICATION_REQUEST";
export const TOGGLE_NOTIFICATION_SUCCESS = "TOGGLE_NOTIFICATION_SUCCESS";
export const TOGGLE_NOTIFICATION_FAILURE = "TOGGLE_NOTIFICATION_FAILURE";

// delete user account
export const DELETE_USER_ACCOUNT_REQUEST = "DELETE_USER_ACCOUNT_REQUEST";
export const DELETE_USER_ACCOUNT_SUCCESS = "DELETE_USER_ACCOUNT_SUCCESS";
export const DELETE_USER_ACCOUNT_FAILURE = "DELETE_USER_ACCOUNT_FAILURE";

// set goals
export const SET_GOALS_REQUEST = "SET_GOALS_REQUEST";
export const SET_GOALS_SUCCESS = "SET_GOALS_SUCCESS";
export const SET_GOALS_FAILURE = "SET_GOALS_FAILURE";

// All Requested Articles
export const ALL_REQUESTED_ARTICLES_REQUEST = "ALL_REQUESTED_ARTICLES_REQUEST";
export const ALL_REQUESTED_ARTICLES_SUCCESS = "ALL_REQUESTED_ARTICLES_SUCCESS";
export const ALL_REQUESTED_ARTICLES_FAILURE = "ALL_REQUESTED_ARTICLES_FAILURE";

// Common Actions
export const START_LOADING_REQUEST = 'START_LOADING_REQUEST';
export const START_LOADING_SUCCESS = 'START_LOADING_SUCCESS';
export const START_LOADING_FAILURE = 'START_LOADING_FAILURE';

export const STOP_LOADING_REQUEST = 'STOP_LOADING_REQUEST';
export const STOP_LOADING_SUCCESS = 'STOP_LOADING_SUCCESS';
export const STOP_LOADING_FAILURE = 'STOP_LOADING_FAILURE';

// Post Categories
export const POST_CATEGORIES_REQUEST = 'POST_CATEGORIES_REQUEST';
export const POST_CATEGORIES_SUCCESS = 'POST_CATEGORIES_SUCCESS';
export const POST_CATEGORIES_FAILURE = 'POST_CATEGORIES_FAILURE';

// Post count 
export const POST_COUNT_REQUEST = 'POST_COUNT_REQUEST';
export const POST_COUNT_SUCCESS = 'POST_COUNT_SUCCESS';
export const POST_COUNT_FAILURE = 'POST_COUNT_FAILURE';

// All post by requested article id
export const POST_BY_REQUESTED_ARTICLE_REQUEST = 'POST_BY_REQUESTED_ARTICLE_REQUEST';
export const POST_BY_REQUESTED_ARTICLE_SUCCESS = 'POST_BY_REQUESTED_ARTICLE_SUCCESS';
export const POST_BY_REQUESTED_ARTICLE_FAILURE = 'POST_BY_REQUESTED_ARTICLE_FAILURE';

// My Picked Articles
export const MY_PICKED_ARTICLES_REQUEST = 'MY_PICKED_ARTICLES_REQUEST';
export const MY_PICKED_ARTICLES_SUCCESS = 'MY_PICKED_ARTICLES_SUCCESS';
export const MY_PICKED_ARTICLES_FAILURE = 'MY_PICKED_ARTICLES_FAILURE';

// request article
export const REQUEST_ARTICLE_REQUEST = 'REQUEST_ARTICLE_REQUEST';
export const REQUEST_ARTICLE_SUCCESS = 'REQUEST_ARTICLE_SUCCESS';
export const REQUEST_ARTICLE_FAILURE = 'REQUEST_ARTICLE_FAILURE';

// updated request article
export const UPDATE_REQUEST_ARTICLE_REQUEST = 'UPDATE_REQUEST_ARTICLE_REQUEST';
export const UPDATE_REQUEST_ARTICLE_SUCCESS = 'UPDATE_REQUEST_ARTICLE_SUCCESS';
export const UPDATE_REQUEST_ARTICLE_FAILURE = 'UPDATE_REQUEST_ARTICLE_FAILURE';

export const SET_INACTIVE_TIMESTAMP = 'SET_INACTIVE_TIMESTAMP';
